baseURL = "http://visualprogramming.net/"
languageCode = "en-us"
title = "Visualprogramming.net"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-creative-theme-master"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Visualprogramming.net - vvvv gamma"
	description = "vvvv gamma"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Visualprogramming.net"

		[params.navigation.links]
			about     = "Download"
			services  = "Documentation"
			portfolio = "Blog"
			licensing = "Licensing"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "vvvv gamma"
		subtitle   = "[vvvv gamma](//visualprogramming.net) VL is a new visual programming language supported in vvvv that combines dataflow paradigms with features from object-oriented programming. It builds directly to the .NET Intermediate Language and can also consume .NET libraries."
		buttonText = "Find out more"

	# About section
	[params.about]
		headline    = "Get vvvv gamma"
		description = "Get your [vvvv gamma preview](//vvvv.org/blog/vvvv-gamma-2019.1-preview)"

		[params.about.button]
			text  = "Download"
			link = "https://vvvv.org/blog/vvvv-gamma-2019.1-preview"


# Service section
[params.licensing]
	headline = "Our Licensing model"
	description ="vvvv is free for evaluation and non-commercial use.</br>For all commercial applications, you need to buy a license. </br></br>Commercial use means that the work done with vvvv is primarily intended for or directed toward commercial advantage or private monetary compensation.</br></br>We are well aware of the fact that the distinction between commercial and non-commercial has a somehow blurry boundary. We trust the fair judgement of our users."

	# Service section
	[params.services]
			[[params.services.list]]
			headline = "Documentation"
      icon = "fa-book"
      title = "Documentation"
      description = "Our templates are updated regularly so they don't break."
			link = "https://vvvv.org/blog/vvvv-gamma-2019.1-preview"
			text = "Open Documentation"

      [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Forum"
			description = "Get answers to your questions or find them in existing discussions in the vvvv Forum."
			link = "https://vvvv.org/blog/vvvv-gamma-2019.1-preview"
			text = "Open Forum"

			[[params.services.list]]
      icon = "fas fa-mouse"
      title = "Tutorials"
      description = "Get inspired by a range of videos on a variety of topics spanning from basics to more advanced topics."
			link = "https://vvvv.org/blog/vvvv-gamma-2019.1-preview"
			text = "Open Tutorials"

      [[params.services.list]]
      icon = "fa-heart"
      title = "Made with Love"
      description = "You have to make your websites with love these days!"
			link = "https://vvvv.org/blog/vvvv-gamma-2019.1-preview"
			text = "Link"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
