baseURL = "http://visualprogramming.net/"
languageCode = "en-us"
title = "Visualprogramming.net"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-creative-theme-master"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "visualprogramming.net - vvvv gamma"
	description = "vvvv is a visual programming environment for .NET"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "visualprogramming.net"

		[params.navigation.links]
			download  = "Download"
			Learn		  = "Learn"
			forum			= "Forum"
			gallery		= "Gallery"
			licensing = "Licensing"
			contact   = "Contact"


	# Hero section
		[params.Hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "vvvv"
		subtitle   = "vvvv is a visual live-programming environment that serves you from rapid prototyping to final production. It combines aspects of dataflow and object oriented programming. It can easily be extended by using any .NET library or writing C# code."
		buttonText = "Try it out!"
		buttonLink = "download"

		# Download section

		[params.Download]
		headline = "Download"

		[params.Download.beta]
		headline    = "vvvv beta"
		description = "In development since 2001, vvvv beta has been used by many companies worldwide to create large media environments with physical interfaces, real-time motion graphics, audio and video that can interact with many users simultaneously.<p>We recommend vvvv beta if you need the following:<p><tr><li>3d graphics</li><li>3d physics</li><li>2d physics</li><li>Audio/Video playback</li></tr>"

		[params.Download.beta.button]
		text  = "Download beta"
		link = "https://vvvv.org/downloads"

		[params.Download.gamma]
		headline    = "vvvv gamma"
		description = "In preview since April 2019, vvvv gamma is the next generation of vvvv. While still missing an essential 3d engine it is already much more versatile than vvvv beta in many other areas.<p>We recommend vvvv gamma if you need the following:<p><tr><li>2d graphics</li><li>Integration of .NET libraries</li><li>Async Execution</li></tr>"

		[params.Download.gamma.button]
		text  = "Download gamma"
		link = "https://vvvv.org/blog/vvvv-gamma-2019.1-preview"

		# Gallery section
		[params.Gallery]
		headline    = "Gallery"

	# Learn section
	[params.Learn]

			headline = "Learn"

			[[params.Learn.list]]
			icon = "fa-eye"
			title = "Tutorials"
			description = "Tutorials are step-by-step guides that take you from scratch to a specified goal."
			link = "https://www.youtube.com/playlist?list=PLBTgwgsWWcT_VMMrwsy3Ao7_ubazEGL4s"
			text = "Open Tutorials"

			[[params.Learn.list]]
			headline = "HowTos"
      icon = "fa-lightbulb-o"
      title = "HowTos"
      description = "How-To guides show how to solve a specific problem in a series of steps."
			link = "https://www.youtube.com/playlist?list=PLBTgwgsWWcT-G9lk-IlKLkGZJ9NnXcuBV"
			text = "Open HowTos"

      [[params.Learn.list]]
			icon = "fa fa-bolt"
			title = "Explanation"
			description = "Here we explain the bigger picture providing background and context."
			link = "https://vvvv.gitbooks.io/the-gray-book/content/en/introduction/vl/_language.html"
			text = "Open Explanation"

			[[params.Learn.list]]
      icon = "fa-book"
      title = "Reference"
      description = "The reference guide comprises of technical descriptions of the innards of vvvv."
			link = "https://vvvv.gitbooks.io/the-gray-book/content/en/reference.html"
			text = "Open Reference"

	# Contact section
		[params.contact]
			headline = "Contact"
			description = " "

		[params.contact.imprint]
		headline = "Imprint"
		text ="vvvv - Dießl & Gregor GbR<br>Oranienstrasse 10 <br> 10997 Berlin/Germany<br>VAT: DE275566955<br><br>groupӘvvvv.org"
