[markup]
	[markup.goldmark.renderer]
	      hardWraps = false
	      unsafe = true
	      xhtml = false

baseURL = "https://visualprogramming.net/"
languageCode = "en-us"


# Change the default theme to be use when building the site with Hugo
theme = "hugo-creative-theme-master"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]

		title = "vvvv - visual live-progamming for .NET"
		author = "vvvv group"
		description = "vvvv is a visual live-programming environment for .NET"

		# The path must be relative to the static folder
		favicon = "favicon.ico"

		# Navigation
		[params.navigation]
		brand 		= "visualprogramming.net"

		[params.navigation.links]
		features  = "Features"
		download  = "Download"
		gallery		= "Showcase"
		Learn		  = "Learn"
		community	= "Community"
		licensing = "Licensing"
		contact   = "Contact"

		# Ribbon
		# [params.Ribbon]
		# text 			= "PRELIMINARY"
		# tooltip 	= "A unified website for both vvvv beta and vvvv gamma is still to come. For now find everything about vvvv gamma on this page and go to vvvv.org to learn about vvvv beta."

		# Hero section
		[params.Hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "vvvv"
		subtitle   = "A visual live-programming environment<br/>that takes you from rapid prototyping<br/>to final production."
		tryitButton = "Get it!"
		tryitButtonLink = "Download"
		learnmoreButton = "Learn More"
		learnmoreButtonLink = "Features"
		tagsHeadline = "It claims to be popular for:"
		tags = "#creativecoding, #generativedesign, #interactiondesign, #datavisualization, #computervision, #showcontrol, #physicalcomputing, #datascience, #dotnet"

		# Overview Section
		[params.Overview]
		headline = "Visual Live-Programming with vvvv"
		modalWindowTitle = "Visual Live Programming with vvvv"
		modalFeaturesTitle = "Features"
		button = "More Details"
		buttonLink = "Modal"

		# Download section

		[params.Download]
		headline = "Download"

		[params.Download.beta]
		headline    = "vvvv beta"
		description = "In development since 2001, vvvv beta has been used by many companies worldwide to create large media environments.<p>Recommended for:<p><tr><li>3d Graphics</li><li>Physics</li><li>Audio/Video Playback</li><li>Multiscreen Setups</li><li>Projection Mapping</li><li>Client-Server Setups</li></tr>"

		[params.Download.beta.button]
		text  = "Go to vvvv.org"
		link = "https://vvvv.org/downloads"
		target = "_blank"

		[params.Download.gamma]
		headline    = "vvvv gamma"
		description = "In preview since April 2019, vvvv gamma is the next generation of vvvv, entirely rewritten from scratch.<p>Recommended for:<p><tr><li>2d Graphics</li><li>Computer Vision</li><li>Devices and Protocols</li><li>Multithreading</li><li>Integration of .NET libraries</li><li>Creating Executables</li></tr>"

		[params.Download.gamma.button]
		text  = "Download"
		link = "http://teamcity.vvvv.org/guestAuth/app/rest/builds/id:31856/artifacts/content/vvvv_gamma_2020.1.0_setup.exe"
		version = "(Version: 2020.1)"
		target = "_self"

		#Blog section
		# [params.Blog]
		# headline    = "Showcase"

		[params.Showreel]
		headline = "Showcase"
		subline = "Projects in this showreel were realized mostly with vvvv beta within the past few years."
		vimeo = 371511910

	#Community section
	  [params.Community]
		headline = "Community"

		[[params.Community.list]]
		img = "img/icons/Discourse-32x32_gray.png"
		imgAlt = "vvvv Forum"
		title = "Forum"
		description = "Get answers to your questions or find them in existing discussions in the vvvv forum."
		link = "https://discourse.vvvv.org/c/vvvv-gamma"
		text = "Open Forum"

		[[params.Community.list]]
		img = "img/icons/riot-32x32-black.png"
		imgAlt = "vvvv on Matrix"
		title = "Chat"
		description = "Join us for a chat: Get help 24/7 or just hang out with your fellow patchers."
		link = "https://riot.im/app/#/room/#vvvv:matrix.org"
		text = "Open Riot"

		[[params.Community.list]]
		img = "img/icons/gettogether_logo_w_32x32_gray.png"
		imgAlt = "vvvv GetTogehter"
		title = "Meetups"
		description = "Join us for a meetup: real-world, in-person drinks and presentations around vvvv."
		link = "https://gettogether.community/vvvv/events/"
		text = "Open Gettogether"

	# Learn section
	[params.Learn]

			headline = "Learn"

			[[params.Learn.list]]
			icon = "fa-eye"
			title = "Tutorial Videos"
			description = "Beginners start here: Get a feeling for working with vvvv."
			link = "https://www.youtube.com/playlist?list=PLBTgwgsWWcT_VMMrwsy3Ao7_ubazEGL4s"
			text = "Open Tutorials"

			[[params.Learn.list]]
			headline = "HowTos"
      icon = "fa-lightbulb-o"
      title = "HowTo Videos"
      description = "Specific questions answered step-by-step."
			link = "https://www.youtube.com/playlist?list=PLBTgwgsWWcT-G9lk-IlKLkGZJ9NnXcuBV"
			text = "Open HowTos"

      [[params.Learn.list]]
      icon = "fa-book"
      title = "Reference"
      description = "The manual: Technical descriptions of vvvv in detail."
			link = "https://vvvv.gitbooks.io/the-gray-book/content/en/reference.html"
			text = "Open Reference"

			[[params.Learn.list]]
			icon = "fa fa-bolt"
			title = "Explanations"
			description = "The bigger picture: Providing background and context."
			link = "https://vvvv.gitbooks.io/the-gray-book/content/en/"
			text = "Open Explanation"

	# Contact section
		[params.contact]
			headline = "Contact"
			description = " "

		[params.contact.imprint]
		headline = "Imprint"
		text ="vvvv - Dießl & Gregor GbR<br>Oranienstrasse 10 <br> 10997 Berlin/Germany<br>VAT: DE275566955<br><br>groupӘvvvv.org"
