baseURL = "http://visualprogramming.net/"
languageCode = "en-us"
title = "Visualprogramming.net"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-creative-theme-master"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Visualprogramming.net - vvvv gamma"
	description = "vvvv gamma"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Visualprogramming.net"

		[params.navigation.links]
			about     = "Download"
			services  = "Documentation"
			portfolio = "Documentation"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "vvvv gamma"
		subtitle   = "[vvvv gamma](//visualprogramming.net) VL is a new visual programming language supported in vvvv that combines dataflow paradigms with features from object-oriented programming. It builds directly to the .NET Intermediate Language and can also consume .NET libraries."
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Get vvvv gamma"
		description = "Get your [vvvv gamma preview](//vvvv.org/blog/vvvv-gamma-2019.1-preview)"
		
		[params.about.button]
			text  = "Download"
			link = "https://vvvv.org/blog/vvvv-gamma-2019.1-preview"


	# Service section
	[params.services]
		headline = "Documentation"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Documentation"
            description = "Our templates are updated regularly so they don't break."
			link = "https://vvvv.org/blog/vvvv-gamma-2019.1-preview"
			text = "Documentation"

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Forum"
			description = "You can use this theme as is, or you can make changes!"
			link = "https://vvvv.org/blog/vvvv-gamma-2019.1-preview"
			text = "Forum"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Tutorials"
            description = "We update dependencies to keep things fresh."
			link = "https://vvvv.org/blog/vvvv-gamma-2019.1-preview"
			text = "Tutorials"

        [[params.services.list]]
            icon = "fa-heart"
            title = "Made with Love"
            description = "You have to make your websites with love these days!"
			link = "https://vvvv.org/blog/vvvv-gamma-2019.1-preview"
			text = "Link"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "feedback@startbootstrap.com"

